#Max Memory: 550MB
#Max CPU: 1.5
version: '3'

services:

  api: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    ports:
        - "3001:3000"
    container_name: fsharp-api-2024_q1
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=rinha;Username=postgres;Password=postgres
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '150MB'
        reservations:
          cpus: '0.15'
          memory: '50MB'

  api2:
      <<: *api
      hostname: api02
      ports:
          - "3002:3000"

  db:
    image: "postgres:latest"
    hostname: db
    ports:
        - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c checkpoint_timeout=600 -c checkpoint_completion_target=0.9 -c checkpoint_warning=300ms -c max_wal_size=10MB -c wal_keep_segments=8 -c wal_level=hot_standby -c max_connections=10 -c shared_buffers=50MB -c effective_cache_size=100MB -c work_mem=16MB -c maintenance_work_mem=80MB -c max_worker_processes=10 -c max_parallel_workers_per_gather=6 -c max_parallel_workers=10'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '100MB'
        reservations:
          cpus: '0.05'
          memory: '30MB'

  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '10MB'
        reservations:
          cpus: '0.05'
          memory: '10MB'
